// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p23
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_codegen.cpp:373


#include "RtpsRpcC.h"
#include "tao/CDR.h"

#if !defined (__ACE_INLINE__)
#include "RtpsRpcC.inl"
#endif /* !defined INLINE */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_visitor_structure\cdr_op_cs.cpp:51



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const DDS::SampleIdentity &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.writer_guid) &&
    (strm << _tao_aggregate.sequence_number);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    DDS::SampleIdentity &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.writer_guid) &&
    (strm >> _tao_aggregate.sequence_number);
}

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_visitor_enum\cdr_op_cs.cpp:36



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (TAO_OutputCDR &strm, DDS::RPC::RemoteExceptionCode_t _tao_enumerator)
{
  return strm << static_cast< ::CORBA::ULong> (_tao_enumerator);
}

::CORBA::Boolean operator>> (TAO_InputCDR &strm, DDS::RPC::RemoteExceptionCode_t & _tao_enumerator)
{
  ::CORBA::ULong _tao_temp = 0;
  ::CORBA::Boolean const _tao_success = strm >> _tao_temp;
  
  if (_tao_success)
    {
      _tao_enumerator = static_cast<DDS::RPC::RemoteExceptionCode_t> (_tao_temp);
    }
  
  return _tao_success;
}

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_visitor_structure\cdr_op_cs.cpp:51



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const DDS::RPC::RequestHeader &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.requestId) &&
    (strm << ACE_OutputCDR::from_string (_tao_aggregate.instanceName.in (), 255));
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    DDS::RPC::RequestHeader &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.requestId) &&
    (strm >> ACE_InputCDR::to_string (_tao_aggregate.instanceName.out (), 255));
}

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_visitor_structure\cdr_op_cs.cpp:51



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const DDS::RPC::ReplyHeader &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.relatedRequestId) &&
    (strm << _tao_aggregate.remoteEx);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    DDS::RPC::ReplyHeader &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.relatedRequestId) &&
    (strm >> _tao_aggregate.remoteEx);
}

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL





OPENDDS_END_VERSIONED_NAMESPACE_DECL


