
// -*- C++ -*-
// $Id$
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.py

#define CIAO_MAJOR_VERSION 1
#define CIAO_MINOR_VERSION 2
#define CIAO_BETA_VERSION 0
#define CIAO_VERSION "1.2a_p23"
#define CIAO_OCI_PATCHLEVEL 23
#define CIAO_OCI_REV a
