// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p23
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_codegen.cpp:373


#include "RelayTypeSupportC.h"
#include "tao/CDR.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "RelayTypeSupportC.inl"
#endif /* !defined INLINE */
// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:50



// Traits specializations for RtpsRelay::RelayPartitionsTypeSupport.

RtpsRelay::RelayPartitionsTypeSupport_ptr
TAO::Objref_Traits<RtpsRelay::RelayPartitionsTypeSupport>::duplicate (
    RtpsRelay::RelayPartitionsTypeSupport_ptr p)
{
  return RtpsRelay::RelayPartitionsTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<RtpsRelay::RelayPartitionsTypeSupport>::release (
    RtpsRelay::RelayPartitionsTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

RtpsRelay::RelayPartitionsTypeSupport_ptr
TAO::Objref_Traits<RtpsRelay::RelayPartitionsTypeSupport>::nil (void)
{
  return RtpsRelay::RelayPartitionsTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RtpsRelay::RelayPartitionsTypeSupport>::marshal (
    const RtpsRelay::RelayPartitionsTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

RtpsRelay::RelayPartitionsTypeSupport::RelayPartitionsTypeSupport (void)
{}

RtpsRelay::RelayPartitionsTypeSupport::~RelayPartitionsTypeSupport (void)
{
}

RtpsRelay::RelayPartitionsTypeSupport_ptr
RtpsRelay::RelayPartitionsTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayPartitionsTypeSupport::_duplicate (
      dynamic_cast<RelayPartitionsTypeSupport_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayPartitionsTypeSupport_ptr
RtpsRelay::RelayPartitionsTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayPartitionsTypeSupport::_duplicate (
      dynamic_cast<RelayPartitionsTypeSupport_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayPartitionsTypeSupport_ptr
RtpsRelay::RelayPartitionsTypeSupport::_nil (void)
{
  return 0;
}

RtpsRelay::RelayPartitionsTypeSupport_ptr
RtpsRelay::RelayPartitionsTypeSupport::_duplicate (RelayPartitionsTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RtpsRelay::RelayPartitionsTypeSupport::_tao_release (RelayPartitionsTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RtpsRelay::RelayPartitionsTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:RtpsRelay/RelayPartitionsTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RtpsRelay::RelayPartitionsTypeSupport::_interface_repository_id (void) const
{
  return "IDL:RtpsRelay/RelayPartitionsTypeSupport:1.0";
}

::CORBA::Boolean
RtpsRelay::RelayPartitionsTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:50



// Traits specializations for RtpsRelay::RelayPartitionsDataWriter.

RtpsRelay::RelayPartitionsDataWriter_ptr
TAO::Objref_Traits<RtpsRelay::RelayPartitionsDataWriter>::duplicate (
    RtpsRelay::RelayPartitionsDataWriter_ptr p)
{
  return RtpsRelay::RelayPartitionsDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<RtpsRelay::RelayPartitionsDataWriter>::release (
    RtpsRelay::RelayPartitionsDataWriter_ptr p)
{
  ::CORBA::release (p);
}

RtpsRelay::RelayPartitionsDataWriter_ptr
TAO::Objref_Traits<RtpsRelay::RelayPartitionsDataWriter>::nil (void)
{
  return RtpsRelay::RelayPartitionsDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RtpsRelay::RelayPartitionsDataWriter>::marshal (
    const RtpsRelay::RelayPartitionsDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

RtpsRelay::RelayPartitionsDataWriter::RelayPartitionsDataWriter (void)
{}

RtpsRelay::RelayPartitionsDataWriter::~RelayPartitionsDataWriter (void)
{
}

RtpsRelay::RelayPartitionsDataWriter_ptr
RtpsRelay::RelayPartitionsDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayPartitionsDataWriter::_duplicate (
      dynamic_cast<RelayPartitionsDataWriter_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayPartitionsDataWriter_ptr
RtpsRelay::RelayPartitionsDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayPartitionsDataWriter::_duplicate (
      dynamic_cast<RelayPartitionsDataWriter_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayPartitionsDataWriter_ptr
RtpsRelay::RelayPartitionsDataWriter::_nil (void)
{
  return 0;
}

RtpsRelay::RelayPartitionsDataWriter_ptr
RtpsRelay::RelayPartitionsDataWriter::_duplicate (RelayPartitionsDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RtpsRelay::RelayPartitionsDataWriter::_tao_release (RelayPartitionsDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RtpsRelay::RelayPartitionsDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:RtpsRelay/RelayPartitionsDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RtpsRelay::RelayPartitionsDataWriter::_interface_repository_id (void) const
{
  return "IDL:RtpsRelay/RelayPartitionsDataWriter:1.0";
}

::CORBA::Boolean
RtpsRelay::RelayPartitionsDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:50



// Traits specializations for RtpsRelay::RelayPartitionsDataReader.

RtpsRelay::RelayPartitionsDataReader_ptr
TAO::Objref_Traits<RtpsRelay::RelayPartitionsDataReader>::duplicate (
    RtpsRelay::RelayPartitionsDataReader_ptr p)
{
  return RtpsRelay::RelayPartitionsDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<RtpsRelay::RelayPartitionsDataReader>::release (
    RtpsRelay::RelayPartitionsDataReader_ptr p)
{
  ::CORBA::release (p);
}

RtpsRelay::RelayPartitionsDataReader_ptr
TAO::Objref_Traits<RtpsRelay::RelayPartitionsDataReader>::nil (void)
{
  return RtpsRelay::RelayPartitionsDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RtpsRelay::RelayPartitionsDataReader>::marshal (
    const RtpsRelay::RelayPartitionsDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

RtpsRelay::RelayPartitionsDataReader::RelayPartitionsDataReader (void)
{}

RtpsRelay::RelayPartitionsDataReader::~RelayPartitionsDataReader (void)
{
}

RtpsRelay::RelayPartitionsDataReader_ptr
RtpsRelay::RelayPartitionsDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayPartitionsDataReader::_duplicate (
      dynamic_cast<RelayPartitionsDataReader_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayPartitionsDataReader_ptr
RtpsRelay::RelayPartitionsDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayPartitionsDataReader::_duplicate (
      dynamic_cast<RelayPartitionsDataReader_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayPartitionsDataReader_ptr
RtpsRelay::RelayPartitionsDataReader::_nil (void)
{
  return 0;
}

RtpsRelay::RelayPartitionsDataReader_ptr
RtpsRelay::RelayPartitionsDataReader::_duplicate (RelayPartitionsDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RtpsRelay::RelayPartitionsDataReader::_tao_release (RelayPartitionsDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RtpsRelay::RelayPartitionsDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:RtpsRelay/RelayPartitionsDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RtpsRelay::RelayPartitionsDataReader::_interface_repository_id (void) const
{
  return "IDL:RtpsRelay/RelayPartitionsDataReader:1.0";
}

::CORBA::Boolean
RtpsRelay::RelayPartitionsDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:50



// Traits specializations for RtpsRelay::RelayAddressTypeSupport.

RtpsRelay::RelayAddressTypeSupport_ptr
TAO::Objref_Traits<RtpsRelay::RelayAddressTypeSupport>::duplicate (
    RtpsRelay::RelayAddressTypeSupport_ptr p)
{
  return RtpsRelay::RelayAddressTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<RtpsRelay::RelayAddressTypeSupport>::release (
    RtpsRelay::RelayAddressTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

RtpsRelay::RelayAddressTypeSupport_ptr
TAO::Objref_Traits<RtpsRelay::RelayAddressTypeSupport>::nil (void)
{
  return RtpsRelay::RelayAddressTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RtpsRelay::RelayAddressTypeSupport>::marshal (
    const RtpsRelay::RelayAddressTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

RtpsRelay::RelayAddressTypeSupport::RelayAddressTypeSupport (void)
{}

RtpsRelay::RelayAddressTypeSupport::~RelayAddressTypeSupport (void)
{
}

RtpsRelay::RelayAddressTypeSupport_ptr
RtpsRelay::RelayAddressTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayAddressTypeSupport::_duplicate (
      dynamic_cast<RelayAddressTypeSupport_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayAddressTypeSupport_ptr
RtpsRelay::RelayAddressTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayAddressTypeSupport::_duplicate (
      dynamic_cast<RelayAddressTypeSupport_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayAddressTypeSupport_ptr
RtpsRelay::RelayAddressTypeSupport::_nil (void)
{
  return 0;
}

RtpsRelay::RelayAddressTypeSupport_ptr
RtpsRelay::RelayAddressTypeSupport::_duplicate (RelayAddressTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RtpsRelay::RelayAddressTypeSupport::_tao_release (RelayAddressTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RtpsRelay::RelayAddressTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:RtpsRelay/RelayAddressTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RtpsRelay::RelayAddressTypeSupport::_interface_repository_id (void) const
{
  return "IDL:RtpsRelay/RelayAddressTypeSupport:1.0";
}

::CORBA::Boolean
RtpsRelay::RelayAddressTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:50



// Traits specializations for RtpsRelay::RelayAddressDataWriter.

RtpsRelay::RelayAddressDataWriter_ptr
TAO::Objref_Traits<RtpsRelay::RelayAddressDataWriter>::duplicate (
    RtpsRelay::RelayAddressDataWriter_ptr p)
{
  return RtpsRelay::RelayAddressDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<RtpsRelay::RelayAddressDataWriter>::release (
    RtpsRelay::RelayAddressDataWriter_ptr p)
{
  ::CORBA::release (p);
}

RtpsRelay::RelayAddressDataWriter_ptr
TAO::Objref_Traits<RtpsRelay::RelayAddressDataWriter>::nil (void)
{
  return RtpsRelay::RelayAddressDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RtpsRelay::RelayAddressDataWriter>::marshal (
    const RtpsRelay::RelayAddressDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

RtpsRelay::RelayAddressDataWriter::RelayAddressDataWriter (void)
{}

RtpsRelay::RelayAddressDataWriter::~RelayAddressDataWriter (void)
{
}

RtpsRelay::RelayAddressDataWriter_ptr
RtpsRelay::RelayAddressDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayAddressDataWriter::_duplicate (
      dynamic_cast<RelayAddressDataWriter_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayAddressDataWriter_ptr
RtpsRelay::RelayAddressDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayAddressDataWriter::_duplicate (
      dynamic_cast<RelayAddressDataWriter_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayAddressDataWriter_ptr
RtpsRelay::RelayAddressDataWriter::_nil (void)
{
  return 0;
}

RtpsRelay::RelayAddressDataWriter_ptr
RtpsRelay::RelayAddressDataWriter::_duplicate (RelayAddressDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RtpsRelay::RelayAddressDataWriter::_tao_release (RelayAddressDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RtpsRelay::RelayAddressDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:RtpsRelay/RelayAddressDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RtpsRelay::RelayAddressDataWriter::_interface_repository_id (void) const
{
  return "IDL:RtpsRelay/RelayAddressDataWriter:1.0";
}

::CORBA::Boolean
RtpsRelay::RelayAddressDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:50



// Traits specializations for RtpsRelay::RelayAddressDataReader.

RtpsRelay::RelayAddressDataReader_ptr
TAO::Objref_Traits<RtpsRelay::RelayAddressDataReader>::duplicate (
    RtpsRelay::RelayAddressDataReader_ptr p)
{
  return RtpsRelay::RelayAddressDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<RtpsRelay::RelayAddressDataReader>::release (
    RtpsRelay::RelayAddressDataReader_ptr p)
{
  ::CORBA::release (p);
}

RtpsRelay::RelayAddressDataReader_ptr
TAO::Objref_Traits<RtpsRelay::RelayAddressDataReader>::nil (void)
{
  return RtpsRelay::RelayAddressDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RtpsRelay::RelayAddressDataReader>::marshal (
    const RtpsRelay::RelayAddressDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

RtpsRelay::RelayAddressDataReader::RelayAddressDataReader (void)
{}

RtpsRelay::RelayAddressDataReader::~RelayAddressDataReader (void)
{
}

RtpsRelay::RelayAddressDataReader_ptr
RtpsRelay::RelayAddressDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayAddressDataReader::_duplicate (
      dynamic_cast<RelayAddressDataReader_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayAddressDataReader_ptr
RtpsRelay::RelayAddressDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayAddressDataReader::_duplicate (
      dynamic_cast<RelayAddressDataReader_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayAddressDataReader_ptr
RtpsRelay::RelayAddressDataReader::_nil (void)
{
  return 0;
}

RtpsRelay::RelayAddressDataReader_ptr
RtpsRelay::RelayAddressDataReader::_duplicate (RelayAddressDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RtpsRelay::RelayAddressDataReader::_tao_release (RelayAddressDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RtpsRelay::RelayAddressDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:RtpsRelay/RelayAddressDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RtpsRelay::RelayAddressDataReader::_interface_repository_id (void) const
{
  return "IDL:RtpsRelay/RelayAddressDataReader:1.0";
}

::CORBA::Boolean
RtpsRelay::RelayAddressDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:50



// Traits specializations for RtpsRelay::RelayStatusTypeSupport.

RtpsRelay::RelayStatusTypeSupport_ptr
TAO::Objref_Traits<RtpsRelay::RelayStatusTypeSupport>::duplicate (
    RtpsRelay::RelayStatusTypeSupport_ptr p)
{
  return RtpsRelay::RelayStatusTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<RtpsRelay::RelayStatusTypeSupport>::release (
    RtpsRelay::RelayStatusTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

RtpsRelay::RelayStatusTypeSupport_ptr
TAO::Objref_Traits<RtpsRelay::RelayStatusTypeSupport>::nil (void)
{
  return RtpsRelay::RelayStatusTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RtpsRelay::RelayStatusTypeSupport>::marshal (
    const RtpsRelay::RelayStatusTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

RtpsRelay::RelayStatusTypeSupport::RelayStatusTypeSupport (void)
{}

RtpsRelay::RelayStatusTypeSupport::~RelayStatusTypeSupport (void)
{
}

RtpsRelay::RelayStatusTypeSupport_ptr
RtpsRelay::RelayStatusTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayStatusTypeSupport::_duplicate (
      dynamic_cast<RelayStatusTypeSupport_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayStatusTypeSupport_ptr
RtpsRelay::RelayStatusTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayStatusTypeSupport::_duplicate (
      dynamic_cast<RelayStatusTypeSupport_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayStatusTypeSupport_ptr
RtpsRelay::RelayStatusTypeSupport::_nil (void)
{
  return 0;
}

RtpsRelay::RelayStatusTypeSupport_ptr
RtpsRelay::RelayStatusTypeSupport::_duplicate (RelayStatusTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RtpsRelay::RelayStatusTypeSupport::_tao_release (RelayStatusTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RtpsRelay::RelayStatusTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:RtpsRelay/RelayStatusTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RtpsRelay::RelayStatusTypeSupport::_interface_repository_id (void) const
{
  return "IDL:RtpsRelay/RelayStatusTypeSupport:1.0";
}

::CORBA::Boolean
RtpsRelay::RelayStatusTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:50



// Traits specializations for RtpsRelay::RelayStatusDataWriter.

RtpsRelay::RelayStatusDataWriter_ptr
TAO::Objref_Traits<RtpsRelay::RelayStatusDataWriter>::duplicate (
    RtpsRelay::RelayStatusDataWriter_ptr p)
{
  return RtpsRelay::RelayStatusDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<RtpsRelay::RelayStatusDataWriter>::release (
    RtpsRelay::RelayStatusDataWriter_ptr p)
{
  ::CORBA::release (p);
}

RtpsRelay::RelayStatusDataWriter_ptr
TAO::Objref_Traits<RtpsRelay::RelayStatusDataWriter>::nil (void)
{
  return RtpsRelay::RelayStatusDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RtpsRelay::RelayStatusDataWriter>::marshal (
    const RtpsRelay::RelayStatusDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

RtpsRelay::RelayStatusDataWriter::RelayStatusDataWriter (void)
{}

RtpsRelay::RelayStatusDataWriter::~RelayStatusDataWriter (void)
{
}

RtpsRelay::RelayStatusDataWriter_ptr
RtpsRelay::RelayStatusDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayStatusDataWriter::_duplicate (
      dynamic_cast<RelayStatusDataWriter_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayStatusDataWriter_ptr
RtpsRelay::RelayStatusDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayStatusDataWriter::_duplicate (
      dynamic_cast<RelayStatusDataWriter_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayStatusDataWriter_ptr
RtpsRelay::RelayStatusDataWriter::_nil (void)
{
  return 0;
}

RtpsRelay::RelayStatusDataWriter_ptr
RtpsRelay::RelayStatusDataWriter::_duplicate (RelayStatusDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RtpsRelay::RelayStatusDataWriter::_tao_release (RelayStatusDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RtpsRelay::RelayStatusDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:RtpsRelay/RelayStatusDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RtpsRelay::RelayStatusDataWriter::_interface_repository_id (void) const
{
  return "IDL:RtpsRelay/RelayStatusDataWriter:1.0";
}

::CORBA::Boolean
RtpsRelay::RelayStatusDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:50



// Traits specializations for RtpsRelay::RelayStatusDataReader.

RtpsRelay::RelayStatusDataReader_ptr
TAO::Objref_Traits<RtpsRelay::RelayStatusDataReader>::duplicate (
    RtpsRelay::RelayStatusDataReader_ptr p)
{
  return RtpsRelay::RelayStatusDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<RtpsRelay::RelayStatusDataReader>::release (
    RtpsRelay::RelayStatusDataReader_ptr p)
{
  ::CORBA::release (p);
}

RtpsRelay::RelayStatusDataReader_ptr
TAO::Objref_Traits<RtpsRelay::RelayStatusDataReader>::nil (void)
{
  return RtpsRelay::RelayStatusDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RtpsRelay::RelayStatusDataReader>::marshal (
    const RtpsRelay::RelayStatusDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

RtpsRelay::RelayStatusDataReader::RelayStatusDataReader (void)
{}

RtpsRelay::RelayStatusDataReader::~RelayStatusDataReader (void)
{
}

RtpsRelay::RelayStatusDataReader_ptr
RtpsRelay::RelayStatusDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayStatusDataReader::_duplicate (
      dynamic_cast<RelayStatusDataReader_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayStatusDataReader_ptr
RtpsRelay::RelayStatusDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayStatusDataReader::_duplicate (
      dynamic_cast<RelayStatusDataReader_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayStatusDataReader_ptr
RtpsRelay::RelayStatusDataReader::_nil (void)
{
  return 0;
}

RtpsRelay::RelayStatusDataReader_ptr
RtpsRelay::RelayStatusDataReader::_duplicate (RelayStatusDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RtpsRelay::RelayStatusDataReader::_tao_release (RelayStatusDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RtpsRelay::RelayStatusDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:RtpsRelay/RelayStatusDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RtpsRelay::RelayStatusDataReader::_interface_repository_id (void) const
{
  return "IDL:RtpsRelay/RelayStatusDataReader:1.0";
}

::CORBA::Boolean
RtpsRelay::RelayStatusDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:50



// Traits specializations for RtpsRelay::RelayParticipantStatusTypeSupport.

RtpsRelay::RelayParticipantStatusTypeSupport_ptr
TAO::Objref_Traits<RtpsRelay::RelayParticipantStatusTypeSupport>::duplicate (
    RtpsRelay::RelayParticipantStatusTypeSupport_ptr p)
{
  return RtpsRelay::RelayParticipantStatusTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<RtpsRelay::RelayParticipantStatusTypeSupport>::release (
    RtpsRelay::RelayParticipantStatusTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

RtpsRelay::RelayParticipantStatusTypeSupport_ptr
TAO::Objref_Traits<RtpsRelay::RelayParticipantStatusTypeSupport>::nil (void)
{
  return RtpsRelay::RelayParticipantStatusTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RtpsRelay::RelayParticipantStatusTypeSupport>::marshal (
    const RtpsRelay::RelayParticipantStatusTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

RtpsRelay::RelayParticipantStatusTypeSupport::RelayParticipantStatusTypeSupport (void)
{}

RtpsRelay::RelayParticipantStatusTypeSupport::~RelayParticipantStatusTypeSupport (void)
{
}

RtpsRelay::RelayParticipantStatusTypeSupport_ptr
RtpsRelay::RelayParticipantStatusTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayParticipantStatusTypeSupport::_duplicate (
      dynamic_cast<RelayParticipantStatusTypeSupport_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayParticipantStatusTypeSupport_ptr
RtpsRelay::RelayParticipantStatusTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayParticipantStatusTypeSupport::_duplicate (
      dynamic_cast<RelayParticipantStatusTypeSupport_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayParticipantStatusTypeSupport_ptr
RtpsRelay::RelayParticipantStatusTypeSupport::_nil (void)
{
  return 0;
}

RtpsRelay::RelayParticipantStatusTypeSupport_ptr
RtpsRelay::RelayParticipantStatusTypeSupport::_duplicate (RelayParticipantStatusTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RtpsRelay::RelayParticipantStatusTypeSupport::_tao_release (RelayParticipantStatusTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RtpsRelay::RelayParticipantStatusTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:RtpsRelay/RelayParticipantStatusTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RtpsRelay::RelayParticipantStatusTypeSupport::_interface_repository_id (void) const
{
  return "IDL:RtpsRelay/RelayParticipantStatusTypeSupport:1.0";
}

::CORBA::Boolean
RtpsRelay::RelayParticipantStatusTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:50



// Traits specializations for RtpsRelay::RelayParticipantStatusDataWriter.

RtpsRelay::RelayParticipantStatusDataWriter_ptr
TAO::Objref_Traits<RtpsRelay::RelayParticipantStatusDataWriter>::duplicate (
    RtpsRelay::RelayParticipantStatusDataWriter_ptr p)
{
  return RtpsRelay::RelayParticipantStatusDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<RtpsRelay::RelayParticipantStatusDataWriter>::release (
    RtpsRelay::RelayParticipantStatusDataWriter_ptr p)
{
  ::CORBA::release (p);
}

RtpsRelay::RelayParticipantStatusDataWriter_ptr
TAO::Objref_Traits<RtpsRelay::RelayParticipantStatusDataWriter>::nil (void)
{
  return RtpsRelay::RelayParticipantStatusDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RtpsRelay::RelayParticipantStatusDataWriter>::marshal (
    const RtpsRelay::RelayParticipantStatusDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

RtpsRelay::RelayParticipantStatusDataWriter::RelayParticipantStatusDataWriter (void)
{}

RtpsRelay::RelayParticipantStatusDataWriter::~RelayParticipantStatusDataWriter (void)
{
}

RtpsRelay::RelayParticipantStatusDataWriter_ptr
RtpsRelay::RelayParticipantStatusDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayParticipantStatusDataWriter::_duplicate (
      dynamic_cast<RelayParticipantStatusDataWriter_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayParticipantStatusDataWriter_ptr
RtpsRelay::RelayParticipantStatusDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayParticipantStatusDataWriter::_duplicate (
      dynamic_cast<RelayParticipantStatusDataWriter_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayParticipantStatusDataWriter_ptr
RtpsRelay::RelayParticipantStatusDataWriter::_nil (void)
{
  return 0;
}

RtpsRelay::RelayParticipantStatusDataWriter_ptr
RtpsRelay::RelayParticipantStatusDataWriter::_duplicate (RelayParticipantStatusDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RtpsRelay::RelayParticipantStatusDataWriter::_tao_release (RelayParticipantStatusDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RtpsRelay::RelayParticipantStatusDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:RtpsRelay/RelayParticipantStatusDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RtpsRelay::RelayParticipantStatusDataWriter::_interface_repository_id (void) const
{
  return "IDL:RtpsRelay/RelayParticipantStatusDataWriter:1.0";
}

::CORBA::Boolean
RtpsRelay::RelayParticipantStatusDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:50



// Traits specializations for RtpsRelay::RelayParticipantStatusDataReader.

RtpsRelay::RelayParticipantStatusDataReader_ptr
TAO::Objref_Traits<RtpsRelay::RelayParticipantStatusDataReader>::duplicate (
    RtpsRelay::RelayParticipantStatusDataReader_ptr p)
{
  return RtpsRelay::RelayParticipantStatusDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<RtpsRelay::RelayParticipantStatusDataReader>::release (
    RtpsRelay::RelayParticipantStatusDataReader_ptr p)
{
  ::CORBA::release (p);
}

RtpsRelay::RelayParticipantStatusDataReader_ptr
TAO::Objref_Traits<RtpsRelay::RelayParticipantStatusDataReader>::nil (void)
{
  return RtpsRelay::RelayParticipantStatusDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RtpsRelay::RelayParticipantStatusDataReader>::marshal (
    const RtpsRelay::RelayParticipantStatusDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

RtpsRelay::RelayParticipantStatusDataReader::RelayParticipantStatusDataReader (void)
{}

RtpsRelay::RelayParticipantStatusDataReader::~RelayParticipantStatusDataReader (void)
{
}

RtpsRelay::RelayParticipantStatusDataReader_ptr
RtpsRelay::RelayParticipantStatusDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayParticipantStatusDataReader::_duplicate (
      dynamic_cast<RelayParticipantStatusDataReader_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayParticipantStatusDataReader_ptr
RtpsRelay::RelayParticipantStatusDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayParticipantStatusDataReader::_duplicate (
      dynamic_cast<RelayParticipantStatusDataReader_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayParticipantStatusDataReader_ptr
RtpsRelay::RelayParticipantStatusDataReader::_nil (void)
{
  return 0;
}

RtpsRelay::RelayParticipantStatusDataReader_ptr
RtpsRelay::RelayParticipantStatusDataReader::_duplicate (RelayParticipantStatusDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RtpsRelay::RelayParticipantStatusDataReader::_tao_release (RelayParticipantStatusDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RtpsRelay::RelayParticipantStatusDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:RtpsRelay/RelayParticipantStatusDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RtpsRelay::RelayParticipantStatusDataReader::_interface_repository_id (void) const
{
  return "IDL:RtpsRelay/RelayParticipantStatusDataReader:1.0";
}

::CORBA::Boolean
RtpsRelay::RelayParticipantStatusDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:50



// Traits specializations for RtpsRelay::SpdpReplayTypeSupport.

RtpsRelay::SpdpReplayTypeSupport_ptr
TAO::Objref_Traits<RtpsRelay::SpdpReplayTypeSupport>::duplicate (
    RtpsRelay::SpdpReplayTypeSupport_ptr p)
{
  return RtpsRelay::SpdpReplayTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<RtpsRelay::SpdpReplayTypeSupport>::release (
    RtpsRelay::SpdpReplayTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

RtpsRelay::SpdpReplayTypeSupport_ptr
TAO::Objref_Traits<RtpsRelay::SpdpReplayTypeSupport>::nil (void)
{
  return RtpsRelay::SpdpReplayTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RtpsRelay::SpdpReplayTypeSupport>::marshal (
    const RtpsRelay::SpdpReplayTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

RtpsRelay::SpdpReplayTypeSupport::SpdpReplayTypeSupport (void)
{}

RtpsRelay::SpdpReplayTypeSupport::~SpdpReplayTypeSupport (void)
{
}

RtpsRelay::SpdpReplayTypeSupport_ptr
RtpsRelay::SpdpReplayTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return SpdpReplayTypeSupport::_duplicate (
      dynamic_cast<SpdpReplayTypeSupport_ptr> (_tao_objref)
    );
}

RtpsRelay::SpdpReplayTypeSupport_ptr
RtpsRelay::SpdpReplayTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return SpdpReplayTypeSupport::_duplicate (
      dynamic_cast<SpdpReplayTypeSupport_ptr> (_tao_objref)
    );
}

RtpsRelay::SpdpReplayTypeSupport_ptr
RtpsRelay::SpdpReplayTypeSupport::_nil (void)
{
  return 0;
}

RtpsRelay::SpdpReplayTypeSupport_ptr
RtpsRelay::SpdpReplayTypeSupport::_duplicate (SpdpReplayTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RtpsRelay::SpdpReplayTypeSupport::_tao_release (SpdpReplayTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RtpsRelay::SpdpReplayTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:RtpsRelay/SpdpReplayTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RtpsRelay::SpdpReplayTypeSupport::_interface_repository_id (void) const
{
  return "IDL:RtpsRelay/SpdpReplayTypeSupport:1.0";
}

::CORBA::Boolean
RtpsRelay::SpdpReplayTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:50



// Traits specializations for RtpsRelay::SpdpReplayDataWriter.

RtpsRelay::SpdpReplayDataWriter_ptr
TAO::Objref_Traits<RtpsRelay::SpdpReplayDataWriter>::duplicate (
    RtpsRelay::SpdpReplayDataWriter_ptr p)
{
  return RtpsRelay::SpdpReplayDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<RtpsRelay::SpdpReplayDataWriter>::release (
    RtpsRelay::SpdpReplayDataWriter_ptr p)
{
  ::CORBA::release (p);
}

RtpsRelay::SpdpReplayDataWriter_ptr
TAO::Objref_Traits<RtpsRelay::SpdpReplayDataWriter>::nil (void)
{
  return RtpsRelay::SpdpReplayDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RtpsRelay::SpdpReplayDataWriter>::marshal (
    const RtpsRelay::SpdpReplayDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

RtpsRelay::SpdpReplayDataWriter::SpdpReplayDataWriter (void)
{}

RtpsRelay::SpdpReplayDataWriter::~SpdpReplayDataWriter (void)
{
}

RtpsRelay::SpdpReplayDataWriter_ptr
RtpsRelay::SpdpReplayDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return SpdpReplayDataWriter::_duplicate (
      dynamic_cast<SpdpReplayDataWriter_ptr> (_tao_objref)
    );
}

RtpsRelay::SpdpReplayDataWriter_ptr
RtpsRelay::SpdpReplayDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return SpdpReplayDataWriter::_duplicate (
      dynamic_cast<SpdpReplayDataWriter_ptr> (_tao_objref)
    );
}

RtpsRelay::SpdpReplayDataWriter_ptr
RtpsRelay::SpdpReplayDataWriter::_nil (void)
{
  return 0;
}

RtpsRelay::SpdpReplayDataWriter_ptr
RtpsRelay::SpdpReplayDataWriter::_duplicate (SpdpReplayDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RtpsRelay::SpdpReplayDataWriter::_tao_release (SpdpReplayDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RtpsRelay::SpdpReplayDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:RtpsRelay/SpdpReplayDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RtpsRelay::SpdpReplayDataWriter::_interface_repository_id (void) const
{
  return "IDL:RtpsRelay/SpdpReplayDataWriter:1.0";
}

::CORBA::Boolean
RtpsRelay::SpdpReplayDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:50



// Traits specializations for RtpsRelay::SpdpReplayDataReader.

RtpsRelay::SpdpReplayDataReader_ptr
TAO::Objref_Traits<RtpsRelay::SpdpReplayDataReader>::duplicate (
    RtpsRelay::SpdpReplayDataReader_ptr p)
{
  return RtpsRelay::SpdpReplayDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<RtpsRelay::SpdpReplayDataReader>::release (
    RtpsRelay::SpdpReplayDataReader_ptr p)
{
  ::CORBA::release (p);
}

RtpsRelay::SpdpReplayDataReader_ptr
TAO::Objref_Traits<RtpsRelay::SpdpReplayDataReader>::nil (void)
{
  return RtpsRelay::SpdpReplayDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RtpsRelay::SpdpReplayDataReader>::marshal (
    const RtpsRelay::SpdpReplayDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

RtpsRelay::SpdpReplayDataReader::SpdpReplayDataReader (void)
{}

RtpsRelay::SpdpReplayDataReader::~SpdpReplayDataReader (void)
{
}

RtpsRelay::SpdpReplayDataReader_ptr
RtpsRelay::SpdpReplayDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return SpdpReplayDataReader::_duplicate (
      dynamic_cast<SpdpReplayDataReader_ptr> (_tao_objref)
    );
}

RtpsRelay::SpdpReplayDataReader_ptr
RtpsRelay::SpdpReplayDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return SpdpReplayDataReader::_duplicate (
      dynamic_cast<SpdpReplayDataReader_ptr> (_tao_objref)
    );
}

RtpsRelay::SpdpReplayDataReader_ptr
RtpsRelay::SpdpReplayDataReader::_nil (void)
{
  return 0;
}

RtpsRelay::SpdpReplayDataReader_ptr
RtpsRelay::SpdpReplayDataReader::_duplicate (SpdpReplayDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RtpsRelay::SpdpReplayDataReader::_tao_release (SpdpReplayDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RtpsRelay::SpdpReplayDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:RtpsRelay/SpdpReplayDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RtpsRelay::SpdpReplayDataReader::_interface_repository_id (void) const
{
  return "IDL:RtpsRelay/SpdpReplayDataReader:1.0";
}

::CORBA::Boolean
RtpsRelay::SpdpReplayDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:50



// Traits specializations for RtpsRelay::ParticipantStatisticsTypeSupport.

RtpsRelay::ParticipantStatisticsTypeSupport_ptr
TAO::Objref_Traits<RtpsRelay::ParticipantStatisticsTypeSupport>::duplicate (
    RtpsRelay::ParticipantStatisticsTypeSupport_ptr p)
{
  return RtpsRelay::ParticipantStatisticsTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<RtpsRelay::ParticipantStatisticsTypeSupport>::release (
    RtpsRelay::ParticipantStatisticsTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

RtpsRelay::ParticipantStatisticsTypeSupport_ptr
TAO::Objref_Traits<RtpsRelay::ParticipantStatisticsTypeSupport>::nil (void)
{
  return RtpsRelay::ParticipantStatisticsTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RtpsRelay::ParticipantStatisticsTypeSupport>::marshal (
    const RtpsRelay::ParticipantStatisticsTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

RtpsRelay::ParticipantStatisticsTypeSupport::ParticipantStatisticsTypeSupport (void)
{}

RtpsRelay::ParticipantStatisticsTypeSupport::~ParticipantStatisticsTypeSupport (void)
{
}

RtpsRelay::ParticipantStatisticsTypeSupport_ptr
RtpsRelay::ParticipantStatisticsTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ParticipantStatisticsTypeSupport::_duplicate (
      dynamic_cast<ParticipantStatisticsTypeSupport_ptr> (_tao_objref)
    );
}

RtpsRelay::ParticipantStatisticsTypeSupport_ptr
RtpsRelay::ParticipantStatisticsTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ParticipantStatisticsTypeSupport::_duplicate (
      dynamic_cast<ParticipantStatisticsTypeSupport_ptr> (_tao_objref)
    );
}

RtpsRelay::ParticipantStatisticsTypeSupport_ptr
RtpsRelay::ParticipantStatisticsTypeSupport::_nil (void)
{
  return 0;
}

RtpsRelay::ParticipantStatisticsTypeSupport_ptr
RtpsRelay::ParticipantStatisticsTypeSupport::_duplicate (ParticipantStatisticsTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RtpsRelay::ParticipantStatisticsTypeSupport::_tao_release (ParticipantStatisticsTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RtpsRelay::ParticipantStatisticsTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:RtpsRelay/ParticipantStatisticsTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RtpsRelay::ParticipantStatisticsTypeSupport::_interface_repository_id (void) const
{
  return "IDL:RtpsRelay/ParticipantStatisticsTypeSupport:1.0";
}

::CORBA::Boolean
RtpsRelay::ParticipantStatisticsTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:50



// Traits specializations for RtpsRelay::ParticipantStatisticsDataWriter.

RtpsRelay::ParticipantStatisticsDataWriter_ptr
TAO::Objref_Traits<RtpsRelay::ParticipantStatisticsDataWriter>::duplicate (
    RtpsRelay::ParticipantStatisticsDataWriter_ptr p)
{
  return RtpsRelay::ParticipantStatisticsDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<RtpsRelay::ParticipantStatisticsDataWriter>::release (
    RtpsRelay::ParticipantStatisticsDataWriter_ptr p)
{
  ::CORBA::release (p);
}

RtpsRelay::ParticipantStatisticsDataWriter_ptr
TAO::Objref_Traits<RtpsRelay::ParticipantStatisticsDataWriter>::nil (void)
{
  return RtpsRelay::ParticipantStatisticsDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RtpsRelay::ParticipantStatisticsDataWriter>::marshal (
    const RtpsRelay::ParticipantStatisticsDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

RtpsRelay::ParticipantStatisticsDataWriter::ParticipantStatisticsDataWriter (void)
{}

RtpsRelay::ParticipantStatisticsDataWriter::~ParticipantStatisticsDataWriter (void)
{
}

RtpsRelay::ParticipantStatisticsDataWriter_ptr
RtpsRelay::ParticipantStatisticsDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ParticipantStatisticsDataWriter::_duplicate (
      dynamic_cast<ParticipantStatisticsDataWriter_ptr> (_tao_objref)
    );
}

RtpsRelay::ParticipantStatisticsDataWriter_ptr
RtpsRelay::ParticipantStatisticsDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ParticipantStatisticsDataWriter::_duplicate (
      dynamic_cast<ParticipantStatisticsDataWriter_ptr> (_tao_objref)
    );
}

RtpsRelay::ParticipantStatisticsDataWriter_ptr
RtpsRelay::ParticipantStatisticsDataWriter::_nil (void)
{
  return 0;
}

RtpsRelay::ParticipantStatisticsDataWriter_ptr
RtpsRelay::ParticipantStatisticsDataWriter::_duplicate (ParticipantStatisticsDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RtpsRelay::ParticipantStatisticsDataWriter::_tao_release (ParticipantStatisticsDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RtpsRelay::ParticipantStatisticsDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:RtpsRelay/ParticipantStatisticsDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RtpsRelay::ParticipantStatisticsDataWriter::_interface_repository_id (void) const
{
  return "IDL:RtpsRelay/ParticipantStatisticsDataWriter:1.0";
}

::CORBA::Boolean
RtpsRelay::ParticipantStatisticsDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:50



// Traits specializations for RtpsRelay::ParticipantStatisticsDataReader.

RtpsRelay::ParticipantStatisticsDataReader_ptr
TAO::Objref_Traits<RtpsRelay::ParticipantStatisticsDataReader>::duplicate (
    RtpsRelay::ParticipantStatisticsDataReader_ptr p)
{
  return RtpsRelay::ParticipantStatisticsDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<RtpsRelay::ParticipantStatisticsDataReader>::release (
    RtpsRelay::ParticipantStatisticsDataReader_ptr p)
{
  ::CORBA::release (p);
}

RtpsRelay::ParticipantStatisticsDataReader_ptr
TAO::Objref_Traits<RtpsRelay::ParticipantStatisticsDataReader>::nil (void)
{
  return RtpsRelay::ParticipantStatisticsDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RtpsRelay::ParticipantStatisticsDataReader>::marshal (
    const RtpsRelay::ParticipantStatisticsDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

RtpsRelay::ParticipantStatisticsDataReader::ParticipantStatisticsDataReader (void)
{}

RtpsRelay::ParticipantStatisticsDataReader::~ParticipantStatisticsDataReader (void)
{
}

RtpsRelay::ParticipantStatisticsDataReader_ptr
RtpsRelay::ParticipantStatisticsDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ParticipantStatisticsDataReader::_duplicate (
      dynamic_cast<ParticipantStatisticsDataReader_ptr> (_tao_objref)
    );
}

RtpsRelay::ParticipantStatisticsDataReader_ptr
RtpsRelay::ParticipantStatisticsDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ParticipantStatisticsDataReader::_duplicate (
      dynamic_cast<ParticipantStatisticsDataReader_ptr> (_tao_objref)
    );
}

RtpsRelay::ParticipantStatisticsDataReader_ptr
RtpsRelay::ParticipantStatisticsDataReader::_nil (void)
{
  return 0;
}

RtpsRelay::ParticipantStatisticsDataReader_ptr
RtpsRelay::ParticipantStatisticsDataReader::_duplicate (ParticipantStatisticsDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RtpsRelay::ParticipantStatisticsDataReader::_tao_release (ParticipantStatisticsDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RtpsRelay::ParticipantStatisticsDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:RtpsRelay/ParticipantStatisticsDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RtpsRelay::ParticipantStatisticsDataReader::_interface_repository_id (void) const
{
  return "IDL:RtpsRelay/ParticipantStatisticsDataReader:1.0";
}

::CORBA::Boolean
RtpsRelay::ParticipantStatisticsDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:50



// Traits specializations for RtpsRelay::HandlerStatisticsTypeSupport.

RtpsRelay::HandlerStatisticsTypeSupport_ptr
TAO::Objref_Traits<RtpsRelay::HandlerStatisticsTypeSupport>::duplicate (
    RtpsRelay::HandlerStatisticsTypeSupport_ptr p)
{
  return RtpsRelay::HandlerStatisticsTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<RtpsRelay::HandlerStatisticsTypeSupport>::release (
    RtpsRelay::HandlerStatisticsTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

RtpsRelay::HandlerStatisticsTypeSupport_ptr
TAO::Objref_Traits<RtpsRelay::HandlerStatisticsTypeSupport>::nil (void)
{
  return RtpsRelay::HandlerStatisticsTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RtpsRelay::HandlerStatisticsTypeSupport>::marshal (
    const RtpsRelay::HandlerStatisticsTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

RtpsRelay::HandlerStatisticsTypeSupport::HandlerStatisticsTypeSupport (void)
{}

RtpsRelay::HandlerStatisticsTypeSupport::~HandlerStatisticsTypeSupport (void)
{
}

RtpsRelay::HandlerStatisticsTypeSupport_ptr
RtpsRelay::HandlerStatisticsTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return HandlerStatisticsTypeSupport::_duplicate (
      dynamic_cast<HandlerStatisticsTypeSupport_ptr> (_tao_objref)
    );
}

RtpsRelay::HandlerStatisticsTypeSupport_ptr
RtpsRelay::HandlerStatisticsTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return HandlerStatisticsTypeSupport::_duplicate (
      dynamic_cast<HandlerStatisticsTypeSupport_ptr> (_tao_objref)
    );
}

RtpsRelay::HandlerStatisticsTypeSupport_ptr
RtpsRelay::HandlerStatisticsTypeSupport::_nil (void)
{
  return 0;
}

RtpsRelay::HandlerStatisticsTypeSupport_ptr
RtpsRelay::HandlerStatisticsTypeSupport::_duplicate (HandlerStatisticsTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RtpsRelay::HandlerStatisticsTypeSupport::_tao_release (HandlerStatisticsTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RtpsRelay::HandlerStatisticsTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:RtpsRelay/HandlerStatisticsTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RtpsRelay::HandlerStatisticsTypeSupport::_interface_repository_id (void) const
{
  return "IDL:RtpsRelay/HandlerStatisticsTypeSupport:1.0";
}

::CORBA::Boolean
RtpsRelay::HandlerStatisticsTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:50



// Traits specializations for RtpsRelay::HandlerStatisticsDataWriter.

RtpsRelay::HandlerStatisticsDataWriter_ptr
TAO::Objref_Traits<RtpsRelay::HandlerStatisticsDataWriter>::duplicate (
    RtpsRelay::HandlerStatisticsDataWriter_ptr p)
{
  return RtpsRelay::HandlerStatisticsDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<RtpsRelay::HandlerStatisticsDataWriter>::release (
    RtpsRelay::HandlerStatisticsDataWriter_ptr p)
{
  ::CORBA::release (p);
}

RtpsRelay::HandlerStatisticsDataWriter_ptr
TAO::Objref_Traits<RtpsRelay::HandlerStatisticsDataWriter>::nil (void)
{
  return RtpsRelay::HandlerStatisticsDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RtpsRelay::HandlerStatisticsDataWriter>::marshal (
    const RtpsRelay::HandlerStatisticsDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

RtpsRelay::HandlerStatisticsDataWriter::HandlerStatisticsDataWriter (void)
{}

RtpsRelay::HandlerStatisticsDataWriter::~HandlerStatisticsDataWriter (void)
{
}

RtpsRelay::HandlerStatisticsDataWriter_ptr
RtpsRelay::HandlerStatisticsDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return HandlerStatisticsDataWriter::_duplicate (
      dynamic_cast<HandlerStatisticsDataWriter_ptr> (_tao_objref)
    );
}

RtpsRelay::HandlerStatisticsDataWriter_ptr
RtpsRelay::HandlerStatisticsDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return HandlerStatisticsDataWriter::_duplicate (
      dynamic_cast<HandlerStatisticsDataWriter_ptr> (_tao_objref)
    );
}

RtpsRelay::HandlerStatisticsDataWriter_ptr
RtpsRelay::HandlerStatisticsDataWriter::_nil (void)
{
  return 0;
}

RtpsRelay::HandlerStatisticsDataWriter_ptr
RtpsRelay::HandlerStatisticsDataWriter::_duplicate (HandlerStatisticsDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RtpsRelay::HandlerStatisticsDataWriter::_tao_release (HandlerStatisticsDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RtpsRelay::HandlerStatisticsDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:RtpsRelay/HandlerStatisticsDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RtpsRelay::HandlerStatisticsDataWriter::_interface_repository_id (void) const
{
  return "IDL:RtpsRelay/HandlerStatisticsDataWriter:1.0";
}

::CORBA::Boolean
RtpsRelay::HandlerStatisticsDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:50



// Traits specializations for RtpsRelay::HandlerStatisticsDataReader.

RtpsRelay::HandlerStatisticsDataReader_ptr
TAO::Objref_Traits<RtpsRelay::HandlerStatisticsDataReader>::duplicate (
    RtpsRelay::HandlerStatisticsDataReader_ptr p)
{
  return RtpsRelay::HandlerStatisticsDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<RtpsRelay::HandlerStatisticsDataReader>::release (
    RtpsRelay::HandlerStatisticsDataReader_ptr p)
{
  ::CORBA::release (p);
}

RtpsRelay::HandlerStatisticsDataReader_ptr
TAO::Objref_Traits<RtpsRelay::HandlerStatisticsDataReader>::nil (void)
{
  return RtpsRelay::HandlerStatisticsDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RtpsRelay::HandlerStatisticsDataReader>::marshal (
    const RtpsRelay::HandlerStatisticsDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

RtpsRelay::HandlerStatisticsDataReader::HandlerStatisticsDataReader (void)
{}

RtpsRelay::HandlerStatisticsDataReader::~HandlerStatisticsDataReader (void)
{
}

RtpsRelay::HandlerStatisticsDataReader_ptr
RtpsRelay::HandlerStatisticsDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return HandlerStatisticsDataReader::_duplicate (
      dynamic_cast<HandlerStatisticsDataReader_ptr> (_tao_objref)
    );
}

RtpsRelay::HandlerStatisticsDataReader_ptr
RtpsRelay::HandlerStatisticsDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return HandlerStatisticsDataReader::_duplicate (
      dynamic_cast<HandlerStatisticsDataReader_ptr> (_tao_objref)
    );
}

RtpsRelay::HandlerStatisticsDataReader_ptr
RtpsRelay::HandlerStatisticsDataReader::_nil (void)
{
  return 0;
}

RtpsRelay::HandlerStatisticsDataReader_ptr
RtpsRelay::HandlerStatisticsDataReader::_duplicate (HandlerStatisticsDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RtpsRelay::HandlerStatisticsDataReader::_tao_release (HandlerStatisticsDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RtpsRelay::HandlerStatisticsDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:RtpsRelay/HandlerStatisticsDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RtpsRelay::HandlerStatisticsDataReader::_interface_repository_id (void) const
{
  return "IDL:RtpsRelay/HandlerStatisticsDataReader:1.0";
}

::CORBA::Boolean
RtpsRelay::HandlerStatisticsDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:50



// Traits specializations for RtpsRelay::RelayStatisticsTypeSupport.

RtpsRelay::RelayStatisticsTypeSupport_ptr
TAO::Objref_Traits<RtpsRelay::RelayStatisticsTypeSupport>::duplicate (
    RtpsRelay::RelayStatisticsTypeSupport_ptr p)
{
  return RtpsRelay::RelayStatisticsTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<RtpsRelay::RelayStatisticsTypeSupport>::release (
    RtpsRelay::RelayStatisticsTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

RtpsRelay::RelayStatisticsTypeSupport_ptr
TAO::Objref_Traits<RtpsRelay::RelayStatisticsTypeSupport>::nil (void)
{
  return RtpsRelay::RelayStatisticsTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RtpsRelay::RelayStatisticsTypeSupport>::marshal (
    const RtpsRelay::RelayStatisticsTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

RtpsRelay::RelayStatisticsTypeSupport::RelayStatisticsTypeSupport (void)
{}

RtpsRelay::RelayStatisticsTypeSupport::~RelayStatisticsTypeSupport (void)
{
}

RtpsRelay::RelayStatisticsTypeSupport_ptr
RtpsRelay::RelayStatisticsTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayStatisticsTypeSupport::_duplicate (
      dynamic_cast<RelayStatisticsTypeSupport_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayStatisticsTypeSupport_ptr
RtpsRelay::RelayStatisticsTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayStatisticsTypeSupport::_duplicate (
      dynamic_cast<RelayStatisticsTypeSupport_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayStatisticsTypeSupport_ptr
RtpsRelay::RelayStatisticsTypeSupport::_nil (void)
{
  return 0;
}

RtpsRelay::RelayStatisticsTypeSupport_ptr
RtpsRelay::RelayStatisticsTypeSupport::_duplicate (RelayStatisticsTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RtpsRelay::RelayStatisticsTypeSupport::_tao_release (RelayStatisticsTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RtpsRelay::RelayStatisticsTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:RtpsRelay/RelayStatisticsTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RtpsRelay::RelayStatisticsTypeSupport::_interface_repository_id (void) const
{
  return "IDL:RtpsRelay/RelayStatisticsTypeSupport:1.0";
}

::CORBA::Boolean
RtpsRelay::RelayStatisticsTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:50



// Traits specializations for RtpsRelay::RelayStatisticsDataWriter.

RtpsRelay::RelayStatisticsDataWriter_ptr
TAO::Objref_Traits<RtpsRelay::RelayStatisticsDataWriter>::duplicate (
    RtpsRelay::RelayStatisticsDataWriter_ptr p)
{
  return RtpsRelay::RelayStatisticsDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<RtpsRelay::RelayStatisticsDataWriter>::release (
    RtpsRelay::RelayStatisticsDataWriter_ptr p)
{
  ::CORBA::release (p);
}

RtpsRelay::RelayStatisticsDataWriter_ptr
TAO::Objref_Traits<RtpsRelay::RelayStatisticsDataWriter>::nil (void)
{
  return RtpsRelay::RelayStatisticsDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RtpsRelay::RelayStatisticsDataWriter>::marshal (
    const RtpsRelay::RelayStatisticsDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

RtpsRelay::RelayStatisticsDataWriter::RelayStatisticsDataWriter (void)
{}

RtpsRelay::RelayStatisticsDataWriter::~RelayStatisticsDataWriter (void)
{
}

RtpsRelay::RelayStatisticsDataWriter_ptr
RtpsRelay::RelayStatisticsDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayStatisticsDataWriter::_duplicate (
      dynamic_cast<RelayStatisticsDataWriter_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayStatisticsDataWriter_ptr
RtpsRelay::RelayStatisticsDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayStatisticsDataWriter::_duplicate (
      dynamic_cast<RelayStatisticsDataWriter_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayStatisticsDataWriter_ptr
RtpsRelay::RelayStatisticsDataWriter::_nil (void)
{
  return 0;
}

RtpsRelay::RelayStatisticsDataWriter_ptr
RtpsRelay::RelayStatisticsDataWriter::_duplicate (RelayStatisticsDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RtpsRelay::RelayStatisticsDataWriter::_tao_release (RelayStatisticsDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RtpsRelay::RelayStatisticsDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:RtpsRelay/RelayStatisticsDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RtpsRelay::RelayStatisticsDataWriter::_interface_repository_id (void) const
{
  return "IDL:RtpsRelay/RelayStatisticsDataWriter:1.0";
}

::CORBA::Boolean
RtpsRelay::RelayStatisticsDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// C:\Users\Admin\Downloads\OpenDDS-3.20\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:50



// Traits specializations for RtpsRelay::RelayStatisticsDataReader.

RtpsRelay::RelayStatisticsDataReader_ptr
TAO::Objref_Traits<RtpsRelay::RelayStatisticsDataReader>::duplicate (
    RtpsRelay::RelayStatisticsDataReader_ptr p)
{
  return RtpsRelay::RelayStatisticsDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<RtpsRelay::RelayStatisticsDataReader>::release (
    RtpsRelay::RelayStatisticsDataReader_ptr p)
{
  ::CORBA::release (p);
}

RtpsRelay::RelayStatisticsDataReader_ptr
TAO::Objref_Traits<RtpsRelay::RelayStatisticsDataReader>::nil (void)
{
  return RtpsRelay::RelayStatisticsDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<RtpsRelay::RelayStatisticsDataReader>::marshal (
    const RtpsRelay::RelayStatisticsDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

RtpsRelay::RelayStatisticsDataReader::RelayStatisticsDataReader (void)
{}

RtpsRelay::RelayStatisticsDataReader::~RelayStatisticsDataReader (void)
{
}

RtpsRelay::RelayStatisticsDataReader_ptr
RtpsRelay::RelayStatisticsDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayStatisticsDataReader::_duplicate (
      dynamic_cast<RelayStatisticsDataReader_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayStatisticsDataReader_ptr
RtpsRelay::RelayStatisticsDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RelayStatisticsDataReader::_duplicate (
      dynamic_cast<RelayStatisticsDataReader_ptr> (_tao_objref)
    );
}

RtpsRelay::RelayStatisticsDataReader_ptr
RtpsRelay::RelayStatisticsDataReader::_nil (void)
{
  return 0;
}

RtpsRelay::RelayStatisticsDataReader_ptr
RtpsRelay::RelayStatisticsDataReader::_duplicate (RelayStatisticsDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
RtpsRelay::RelayStatisticsDataReader::_tao_release (RelayStatisticsDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
RtpsRelay::RelayStatisticsDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:RtpsRelay/RelayStatisticsDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* RtpsRelay::RelayStatisticsDataReader::_interface_repository_id (void) const
{
  return "IDL:RtpsRelay/RelayStatisticsDataReader:1.0";
}

::CORBA::Boolean
RtpsRelay::RelayStatisticsDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

