/* -*- C++ -*- */
/* Generated by ..\bin\opendds_idl version 3.20.0 (ACE version 6.2a_p23) running on input file DdsSecurityCore.idl */
#ifndef OPENDDS_IDL_GENERATED_DDSSECURITYCORETYPESUPPORTIMPL_H_OV4DCX
#define OPENDDS_IDL_GENERATED_DDSSECURITYCORETYPESUPPORTIMPL_H_OV4DCX

#include <dds/Version.h>
#if !OPENDDS_VERSION_EXACTLY(3, 20, 0)
#  error "This file should be regenerated with opendds_idl"
#endif
#include <dds/DCPS/Definitions.h>

#include <dds/DdsDcpsC.h>

#include "DdsSecurityCoreC.h"
#include "DdsDcpsGuidC.h"
#include "DdsDcpsInfrastructureC.h"
#include "DdsDcpsPublicationC.h"
#include "DdsDcpsSubscriptionC.h"
#include "DdsSecurityParamsC.h"
#include "dds/DCPS/Service_Participant.h"
#include "dds/DCPS/dcps_export.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: OpenDDS */


/* End MODULE: OpenDDS */
#endif /* OPENDDS_IDL_GENERATED_DDSSECURITYCORETYPESUPPORTIMPL_H_OV4DCX */
