/* -*- C++ -*- */
/* Generated by ..\bin\opendds_idl version 3.20.0 (ACE version 6.2a_p23) running on input file DdsSecurityParams.idl */
#ifndef OPENDDS_IDL_GENERATED_DDSSECURITYPARAMSTYPESUPPORTIMPL_H_S58M5A
#define OPENDDS_IDL_GENERATED_DDSSECURITYPARAMSTYPESUPPORTIMPL_H_S58M5A

#include <dds/Version.h>
#if !OPENDDS_VERSION_EXACTLY(3, 20, 0)
#  error "This file should be regenerated with opendds_idl"
#endif
#include <dds/DCPS/Definitions.h>

#include <dds/DdsDcpsC.h>

#include "DdsSecurityParamsC.h"
#include "DdsDcpsCoreC.h"
#include "dds/DCPS/Service_Participant.h"
#include "dds/DCPS/dcps_export.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: OpenDDS */


/* End MODULE: OpenDDS */
#endif /* OPENDDS_IDL_GENERATED_DDSSECURITYPARAMSTYPESUPPORTIMPL_H_S58M5A */
