
// -*- C++ -*-
// $Id$
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.py

#define TAO_MAJOR_VERSION 2
#define TAO_MINOR_VERSION 2
#define TAO_BETA_VERSION 0
#define TAO_VERSION "2.2a_p23"
#define TAO_OCI_PATCHLEVEL 23
#define TAO_OCI_REV a

